apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  labels:
    app: echofinder
    component: backend
type: Opaque
stringData:
  db-password: echofinder
  hash-prefix-salt: local-prefix-salt
  hash-suffix-salt: local-suffix-salt