apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

labels:
  - pairs:
      app.kubernetes.io/name: echofinder
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
